#!/bin/bash -l

set -e

if [ -f /.dockerenv ]; then
    source ~/.bashrc
    rvm use default
    rvm gemset list
    rvm gemset use rad_consumer
    mv config/database{-jenkins,}.yml
fi

export RAILS_ENV=test
export BUNDLE_WITHOUT=development:build

function run {
    declare -a tests_command=("$@")

    echo ''
    echo "=== Running \`${tests_command[*]}\`"
    if ! ${tests_command[*]}; then
        echo "=== These tests failed."
        exit 1
    fi
}

function info {
    declare -a info_command=("$@")
    echo ''
    echo "=== Running for informational purposes \`${info_command[*]}\`"
    if ! ${info_command[*]}; then
        echo "== This test has errors and/or warnings. Please review results"
    fi
}

run bundle install --quiet
run npm install
run bundle update brakeman --quiet
run bundle exec bowndler install --allow-root
run bundle exec rake db:drop
run bundle exec rake db:create
run bundle exec rake db:schema:load
run bundle exec rspec
run bundle exec cucumber
run ./node_modules/.bin/karma start spec/javascripts/karma.conf.js --single-run
run bundle exec rubocop -DS
run bundle exec brakeman -q --no-pager --ensure-latest

if [ -f /.dockerenv ]; then
  run bundle exec danger --dangerfile=jenkins/Dangerfile --verbose
fi
