name: "CI"
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      GOOGLE_GEOCODER_API_KEY: changeme
      GOOGLE_MAPS_API_KEY: changeme
      ALGOLIA_APP_ID: BHPSLYIJ2L
      ALGOLIA_API_KEY: changeme
      SHOW_ETHICAL_AND_SHARIA_FILTER: true
      SHOW_LANGUAGES_FILTER: true
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 14
      - name: Install bower
        run: npm install -g bower
      - name: Install npm packages
        run: npm install
      - name: Install bowndler packages
        run: bundle exec bowndler update
      - name: Set up database schema
        run: |
          cp "${GITHUB_WORKSPACE}/config/example.database.yml" "${GITHUB_WORKSPACE}/config/database.yml"
          bundle exec rake db:create db:schema:load
      - name: Run tests and lint Ruby
        run: |
          bundle exec rake
      - name: Run JS tests and lint
        run: npm test
